### ISSUE TITLE
Happy Customers

### ISSUE THREAD

**Issue by Samantasingh** [Samantasingh/CPNT-201-A1#8]
### Context

Having guest customers come in and leave with a smile on their faces is very important, that is why it is our main focus. We must ensure they get the right orders, in a timely manner and kindness.

### Tasks

- [ ] Greet customers
- [ ] Take orders correctly
- [ ] Double check before serving orders
- [ ] Resolve any issues in a kind  manner 

### Definition of Done

This goal is done when happy customers are leaving the shop.

- [ ] Smiley faces
- [ ] Returning customers 
- [ ] Good reviews
